name: Update date

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run main script
      run: |
        python main.py
    - name: commit and push
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: update data
        commit_user_name: update data bot
        commit_user_email: sassy.watanabe@gmail.com>
        commit_author: update data bot <sassy.watanabe@gmail.com>
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
